version: "3"
services:
  postgres:
    container_name: pg_container
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"